# see available mappings on src/bender_joy/xbox.py

# pause button
b_pause: 'START'

# increment buttons
b_increment: 'UP'
b_decrement: 'DOWN'

# say phrase button
b_phrase_1: 'LEFT'
b_phrase_2: 'RIGHT'

# text: array of strings
tts_phrases: [
    "hola a todos",
    "soy bender el robot de servicio de la universidad de chile",
    "nac'i en 2007 en la facultad de ciencias f'isicas y matem'aticas",
    "hola humanos, qu'e se siente observar mi grandeza",
    "a mi no me construyeron, yo me dej'e armar por mis esclavos. perd'on. mi equipo",
    "los voy a destruir a todos... perd'on. quise decir que les voy a sonreir a todos",
    "c'omo est'an amigos?",
    "cu'al es el colmo de un robot?... tener nervios de acero ja ja ja ja ",
]