
sensor_msgs/Image image # image to process
# sensor_msgs/RegionOfInterest roi
uchile_msgs/ROIArray[] detection_boxes
sensor_msgs/RegionOfInterest[] detections
---
sensor_msgs/RegionOfInterest[] detections
uchile_msgs/ROIArray[] detection_boxes
float32[] scores
string state