controller_list:
  - name: fake_l_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - l_shoulder_pitch_joint
      - l_shoulder_roll_joint
      - l_shoulder_yaw_joint
      - l_elbow_pitch_joint
      - l_elbow_yaw_joint
      - l_wrist_pitch_joint
  - name: fake_l_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - l_wrist_pitch_joint
      - l_ext_finger_joint
      - l_int_finger_joint
  - name: fake_r_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - r_shoulder_pitch_joint
      - r_shoulder_roll_joint
      - r_shoulder_yaw_joint
      - r_elbow_pitch_joint
      - r_elbow_yaw_joint
      - r_wrist_pitch_joint
  - name: fake_r_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - r_wrist_pitch_joint
      - r_ext_finger_joint
      - r_int_finger_joint
initial:  # Define initial robot poses.
  - group: l_arm
    pose: Home
  - group: r_arm
    pose: Home