# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: l_arm
  joint_model_group_pose: Home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - front_left_wheel_joint
    - front_right_wheel_joint
    - r_shoulder_pitch_joint
    - r_shoulder_roll_joint
    - r_shoulder_yaw_joint
    - r_elbow_pitch_joint
    - r_elbow_yaw_joint
    - r_wrist_pitch_joint
    - r_ext_finger_joint
    - r_int_finger_joint
    - head_yaw_joint
    - head_pitch_joint
    - l_shoulder_pitch_joint
    - l_shoulder_roll_joint
    - l_shoulder_yaw_joint
    - l_elbow_pitch_joint
    - l_elbow_yaw_joint
    - l_wrist_pitch_joint
    - l_ext_finger_joint
    - l_int_finger_joint
    - rear_left_wheel_joint
    - rear_right_wheel_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
r_arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - r_shoulder_pitch_joint
    - r_shoulder_roll_joint
    - r_shoulder_yaw_joint
    - r_elbow_pitch_joint
    - r_elbow_yaw_joint
    - r_wrist_pitch_joint
  gains:
    r_shoulder_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_shoulder_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_shoulder_yaw_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_elbow_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_elbow_yaw_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    r_wrist_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
l_arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - l_shoulder_pitch_joint
    - l_shoulder_roll_joint
    - l_shoulder_yaw_joint
    - l_elbow_pitch_joint
    - l_elbow_yaw_joint
    - l_wrist_pitch_joint
  gains:
    l_shoulder_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l_shoulder_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l_shoulder_yaw_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l_elbow_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l_elbow_yaw_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    l_wrist_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1