octomap_frame: base_link
octomap_resolution: 0.06
max_range: 2.5

sensors:
  - default_sensor
default_sensor:
  filtered_cloud_topic: filtered_cloud
  max_range: 2.5
  max_update_rate: 5.0
  padding_offset: 0.15
  padding_scale: 1.2
  point_cloud_topic: /sam3/scene_cloud
  point_subsample: 12
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
