bender:
  # (Only!) Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Neck controller
  neck_controller:
    type: effort_controllers/JointPositionController
    joint: neck_yaw_joint
    pid: {p: 10.0, i: 0.01, d: 0.0}

  # Asus head controller
  rgbd_head_controller:
    type: effort_controllers/JointPositionController
    joint: rgbd_head_joint
    pid: {p: 5.0, i: 0.01, d: 0.0}

  # Left arm controller
  l_arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - l_shoulder_pitch_joint
      - l_shoulder_roll_joint
      - l_shoulder_yaw_joint
      - l_elbow_pitch_joint
      - l_elbow_yaw_joint
      - l_wrist_pitch_joint
    gains:
      l_shoulder_pitch_joint: {p: 4500.0, i: 130.0, d: 30.0, i_clamp: 100.0}
      l_shoulder_roll_joint: {p: 400.0, i: 50.0, d: 15.0, i_clamp: 60.0}
      l_shoulder_yaw_joint: {p: 30.5, i: 1.5, d: 0.0, i_clamp: 5.0}
      l_elbow_pitch_joint: {p: 4500.0, i: 130.0, d: 15.0, i_clamp: 30.0}
      l_elbow_yaw_joint: {p: 300.0, i: 30.0, d: 0.0, i_clamp: 15.0}
      l_wrist_pitch_joint: {p: 100.0, i: 60.0, d: 10.0, i_clamp: 10.0}

    constraints:
      goal_time: 5.0
      stopped_velocity_tolerance: 1.0
      l_shoulder_pitch_joint: {trajectory: 0.2, goal: 0.2}
      l_shoulder_roll_joint: {trajectory: 0.2, goal: 0.2}
      l_shoulder_yaw_joint: {trajectory: 0.2, goal: 0.2}
      l_elbow_pitch_joint: {trajectory: 0.2, goal: 0.2}
      l_elbow_yaw_joint: {trajectory: 0.2, goal: 0.2}
      l_wrist_pitch_joint: {trajectory: 0.2, goal: 0.2}

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default

  # Right arm controller
  r_arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - r_shoulder_pitch_joint
      - r_shoulder_roll_joint
      - r_shoulder_yaw_joint
      - r_elbow_pitch_joint
      - r_elbow_yaw_joint
      - r_wrist_pitch_joint
    gains:
      r_shoulder_pitch_joint: {p: 4500.0, i: 130.0, d: 30.0, i_clamp: 100.0}
      r_shoulder_roll_joint: {p: 400.0, i: 50.0, d: 15.0, i_clamp: 60.0}
      r_shoulder_yaw_joint: {p: 30.5, i: 1.5, d: 0.0, i_clamp: 5.0}
      r_elbow_pitch_joint: {p: 4500.0, i: 130.0, d: 15.0, i_clamp: 30.0}
      r_elbow_yaw_joint: {p: 300.0, i: 30.0, d: 0.0, i_clamp: 15.0}
      r_wrist_pitch_joint: {p: 100.0, i: 60.0, d: 10.0, i_clamp: 10.0}

    constraints:
      goal_time: 5.0
      stopped_velocity_tolerance: 1.0
      r_shoulder_pitch_joint: {trajectory: 0.2, goal: 0.2}
      r_shoulder_roll_joint: {trajectory: 0.2, goal: 0.2}
      r_shoulder_yaw_joint: {trajectory: 0.2, goal: 0.2}
      r_elbow_pitch_joint: {trajectory: 0.2, goal: 0.2}
      r_elbow_yaw_joint: {trajectory: 0.2, goal: 0.2}
      r_wrist_pitch_joint: {trajectory: 0.2, goal: 0.2}

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default

  # Right gripper controller controller
  r_gripper_controller:
    type: effort_controllers/MultiGripperActionController
    joints:
      - r_int_finger_joint
      - r_ext_finger_joint
    goal_tolerance: 0.1
    max_effort: 2.0
    stalled_velocity_threshold: 0.05
    stall_timeout: 0.2
    gains:
      r_int_finger_joint: {p: 1.0, i: 5.0, d: 0.5, i_clamp_min: 0, i_clamp_max: 0}
      r_ext_finger_joint: {p: 1.0, i: 5.0, d: 0.5, i_clamp_min: 0, i_clamp_max: 0}

  # Left gripper controller controller
  l_gripper_controller:
    type: effort_controllers/MultiGripperActionController
    joints:
      - l_int_finger_joint
      - l_ext_finger_joint
    goal_tolerance: 0.1
    max_effort: 2.0
    stalled_velocity_threshold: 0.5
    stall_timeout: 0.2
    gains:
      l_int_finger_joint: {p: 1.0, i: 5.0, d: 0.5, i_clamp_min: 0, i_clamp_max: 0}
      l_ext_finger_joint: {p: 1.0, i: 5.0, d: 0.5, i_clamp_min: 0, i_clamp_max: 0}