bender:
  # mask head controller
  head_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - head_pitch_joint
      - head_yaw_joint
    gains:
      head_pitch_joint:  {p: 100.0, i: 10.0, d: 0.5, i_clamp: 5.0}
      head_yaw_joint: {p: 100.0, i: 10.0, d: 0.5, i_clamp: 5.0}

    constraints:
      goal_time: 5.0
      stopped_velocity_tolerance: 1.0
      head_pitch_joint: {trajectory: 0.2, goal: 0.2}
      head_yaw_joint: {trajectory: 0.2, goal: 0.2}

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default
