bender:
  # Neck controller
  neck_controller:
    type: effort_controllers/JointPositionController
    joint: neck_yaw_joint
    pid: {p: 10.0, i: 0.01, d: 0.0}

  # Asus head controller
  rgbd_head_controller:
    type: effort_controllers/JointPositionController
    joint: rgbd_head_joint
    pid: {p: 5.0, i: 0.01, d: 0.0}
