bender:
  # Light head controller
  light_head_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - light_head_pitch_joint
      - light_head_yaw_joint
    gains:
      light_head_pitch_joint: {p: 5.0, i: 0.01, d: 0.0}
      light_head_yaw_joint: {p: 5.0, i: 0.01, d: 0.0}

    constraints:
      goal_time: 5.0
      stopped_velocity_tolerance: 1.0
      light_head_pitch_joint: {trajectory: 0.2, goal: 0.2}
      light_head_yaw_joint: {trajectory: 0.2, goal: 0.2}

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default
