r_ext_finger_controller:
  controller:
    module: joint_position_controller
    package: bender_arm_control
    type: JointPositionController
  joint_name: r_ext_finger_joint
  joint_speed: 1.0
  joint_compliance_slope: 128
  joint_compliance_margin: 0
  joint_compliance_punch: 0
  joint_torque_limit: 1.0
  torque_enable_init: False
  enable_pid: True
  p_gain: 0.8
  i_gain: 0.5 
  d_gain: 0.0
  i_clamp: 1.0
  motor:
    id: 17
    init: 815
    max: 950
    min: 810

r_int_finger_controller:
  controller:
    module: joint_position_controller
    package: bender_arm_control
    type: JointPositionController
  joint_name: r_int_finger_joint
  joint_speed: 1.0
  joint_compliance_slope: 128
  joint_compliance_margin: 0
  joint_compliance_punch: 0
  joint_torque_limit: 1.0
  torque_enable_init: False
  enable_pid: True
  p_gain: 0.8
  i_gain: 0.5 
  d_gain: 0.0
  i_clamp: 1.0
  motor:
    id: 18
    init: 490
    max: 355
    min: 495