#!/bin/bash

# Nicolas Marticorena, Rodrigo Munoz
# 12/2016

# Setup

# Color
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
reset=$(tput sgr0)
bold=$(tput bold)
# Line title
title="${bold}[uchile_tf]:${reset}"

# Basic functions

# Load calibration file
load_file ()
{
    local fullpath
    fullpath="$1"
    # Check calibration file
    if [ ! -f "${fullpath}" ]; then
        echo "${title} ${red}Calibration file \"${fullpath}\" not found.${reset}"
        exit 1
    fi
    # Load file in parameter server
    echo "$title Loading calibration file: \"${fullpath}\".${reset}"
    # Se toma la calibracion ultima (pendiente) , falta revisar la fecha mas reciente.
    rosparam load "${fullpath}" /bender/dynamic_tf/
    if [ $? -ne 0 ]; then
        echo "${title} ${red}Error loading file into the parameter server, using default.${reset}"
        exit 1
    fi
    echo "$title Calibration file was successfully loaded.${reset}"
}

load_last_file ()
{
    local calibration_folder filename fullpath
    calibration_folder="$BENDER_WS/base_ws/src/uchile_common/uchile_tf/calibration"
    # Check calibration folder
    if [ ! -d "${calibration_folder}" ]; then
        echo "${title} ${yellow}Calibration folder \"${calibration_folder}\" not found, using default.${reset}"
        exit 0
    fi
    # Get last calibration file (ordered by date)
    filename=$(ls -1r $calibration_folder | head -n 1)
    fullpath="$calibration_folder/$filename"
    # Load file
    load_file $fullpath
}
# Main function
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    -h|--help)
    cat <<EOF
Synopsis:                
    load_calibration [opt] [file]

Description:
    Load calibration file into parameter server.

Options:
    -f, --file      Specify the calibration file.
    -l, --last      Load calibration file (default).
EOF
    exit 0
    ;;
    -f|--file)
    load_file "$2"
    exit 0
    ;;
    -l|--last)
    load_last_file
    exit 0
    ;;
esac
shift # past argument or value
done
# Default
load_last_file
