#!/bin/bash

# Nicolas Marticorena, Rodrigo Munoz
# 12/2016
#
# Obtiene los parametros de dynamic_tf y los guarda en calibation.yaml con la fecha del dia donde se realiza
# run: $ bash calibration_arm/scripts/save_calibration.sh

# Setup

# Color
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
reset=$(tput sgr0)
bold=$(tput bold)
# Line title
title="${bold}[uchile_tf]:${reset}"

# Capture ctrl+c
trap save_file INT

save_file ()
{
    local calibration_folder filename fullpath
    calibration_folder="$BENDER_WS/base_ws/src/uchile_common/uchile_tf/calibration"
    # Check calibration folder
    if [ ! -d "${calibration_folder}" ]; then
        default_folder=$HOME
        echo "${title} ${yellow}Calibration folder \"${calibration_folder}\" not found, calibration file will be saved at \"${default_folder}\".${reset}"
        calibration_folder=$default_folder
    fi
    # Get last calibration file (ordered by date)
    filename=$(ls -1r $calibration_folder | head -n 1)
    fullpath="$calibration_folder/$filename"
    old_calibration_data=""
    if [ -f "${fullpath}" ]; then
        old_calibration_data=$(cat ${fullpath})
    fi
    # Get current calibration values
    calibration_data=$(rosparam get /bender/dynamic_tf/)
    out=$?
    # Check error
    if [ ! $out -eq 0 ];then
        echo "${title} ${red}Error getting calibration data from parameter server.${reset}"
        exit 1
    fi
    # Compare content, save only if is different
    if [ "$calibration_data" != "$old_calibration_data" ];then
        date="$(date +'%s')"
        new_filename="${calibration_folder}/calibration_${date}.yaml"
        echo "$calibration_data" > "$new_filename"
        echo "${title} Calibration file saved at \"${new_filename}\".${reset}"
    fi
    exit 0
}

while [ 1 ]
do
    sleep 0.1
done
