"""autogenerated by genpy from bender_head_arduino/LedCommand2.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class LedCommand2(genpy.Message):
  _md5sum = "57f6c5686c20238314528c60e24feec4"
  _type = "bender_head_arduino/LedCommand2"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string led
int8 r_color
int8 g_color
int8 b_color

"""
  __slots__ = ['led','r_color','g_color','b_color']
  _slot_types = ['string','int8','int8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       led,r_color,g_color,b_color

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LedCommand2, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.led is None:
        self.led = ''
      if self.r_color is None:
        self.r_color = 0
      if self.g_color is None:
        self.g_color = 0
      if self.b_color is None:
        self.b_color = 0
    else:
      self.led = ''
      self.r_color = 0
      self.g_color = 0
      self.b_color = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.led
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3b.pack(_x.r_color, _x.g_color, _x.b_color))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.led = str[start:end].decode('utf-8')
      else:
        self.led = str[start:end]
      _x = self
      start = end
      end += 3
      (_x.r_color, _x.g_color, _x.b_color,) = _struct_3b.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.led
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3b.pack(_x.r_color, _x.g_color, _x.b_color))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.led = str[start:end].decode('utf-8')
      else:
        self.led = str[start:end]
      _x = self
      start = end
      end += 3
      (_x.r_color, _x.g_color, _x.b_color,) = _struct_3b.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3b = struct.Struct("<3b")
