# deadzone: 0.05 
# Amount by which the joystick has to move before it is considered to be off-center.
# relative to an axis normalized between -1 and 1. Thus, 0.1 => 10% of the way to the edge.
# Linux does its own deadzone processing, so in many cases this value can be set to zero. 

# autorepeat_rate: 0.0
# Rate in Hz at which a joystick that has a non-changing state will resend the previously sent message.

# coalesce_interval: 0.001
# Axis events that are received within coalesce_interval (seconds) of each other are sent out in a single
# ROS message. Since the kernel sends each axis motion as a separate event, coalescing greatly reduces the
# rate at which messages are sent. This option can also be used to limit the rate of outgoing messages.
# Button events are always sent out immediately to avoid missing button presses.
deadzone: 0.2