# Config for r_arm, r_gripper and rgbd head
namespace: r_port_manager
serial_ports:
  r_port:
    port_name: "/dev/bender/r_port"
    baud_rate: 200000
    min_motor_id: 1
    max_motor_id: 40
    update_rate: 30