dynamic_emotions:
    veryHappy:
        #LEDs colors
        eyes:
            left: [[black, black, black, black, yellow3, yellow3, black, black, black, black, yellow3, yellow3, yellow3, yellow3, black, black]]
            right: [[black, black, black, black, yellow3, yellow3, black, black, black, black, yellow3, yellow3, yellow3, yellow3, black, black]]
        cheeks:
            left: [[black, black, black, black]]
            right: [[black, black, black, black]]
        #Servos positions in percentage. Meanings: ears: elevation %, eyebrow: 0%->angry & 100%->very surprised, mouth: opening %
        #Orden execution: for each element in array, is set: 
        #left_ear, right_ear, left_eyebrow, right_eyebrow, mouth, and so on with the next element, if exist the element for the part
        #If no element exist for a part, the previous value is preserved for the next updates
        servos:
            left_ear: [40]
            right_ear: [40, 20, 60, 30, 90, 40]
            left_eyebrow: [70]
            right_eyebrow: [70]
            mouth: [60]
        time: 200.0

    sad3:
        eyes:
            left: [[black, black, black, black, blue, blue, black, blue, blue, black, blue, blue, black, black, black, black]]
            right: [[black, black, black, black, blue, blue, black, blue, blue, black, blue, blue, black, black, black, black]]
        cheeks:
            left: [
                [blue, blue, black, black],
                [black, blue, blue, black],
                [blue, black, blue, black],
                [blue, blue, black, black],
                [black, blue, blue, black],
                [blue, black, blue, black],
                [blue, blue, black, black],
                [black, blue, blue, black],
                [blue, black, blue, black]
                ]
            right: [
                [blue, blue, black, black],
                [black, blue, blue, black],
                [blue, black, blue, black],
                [blue, blue, black, black],
                [black, blue, blue, black],
                [blue, black, blue, black],
                [blue, blue, black, black],
                [black, blue, blue, black],
                [blue, black, blue, black]

                ]
        servos:
            left_ear: [10]
            right_ear: [10]
            left_eyebrow: [90]
            right_eyebrow: [90]
            mouth: [0]
        time: 100.0

    eyebrow1313:
        #LEDs colors
        #This are always set first
        #Servos positions in percentage. Meanings: ears: elevation %, eyebrow: 0%->angry & 100%->very surprised, mouth: opening %
        #Orden execution: for each element in array, is set: 
        #left_ear, right_ear, left_eyebrow, right_eyebrow, mouth, and so on with the next element, if exist the element for the part
        #If no element exist for a part, the previous value is preserved for the next updates
        servos:
            left_eyebrow: [80, 50, 80, 50]
            right_eyebrow: [80, 50, 80, 50]
        time: 150.0
    fear:
        #LEDs colors
        eyes:   
            left: [[magenta, blue, magenta, blue, magenta, black, black, black, black, magenta, blue, magenta, blue, black, black, black]]
            right: [[magenta, blue, magenta, blue, magenta, black, black, black, black, magenta, blue, magenta, blue, black, black, black]]
        cheeks:
            left: [[black, black, black, black]]
            right: [[black, black, black, black]]
        #Servos positions in percentage. Meanings: ears: elevation %, eyebrow: 0%->angry & 100%->very surprised, mouth: opening %
        servos:
            left_ear: [0]
            right_ear: [0]
            left_eyebrow: [80, 85, 80, 85, 78, 83,80, 85, 80, 85, 78, 83, 80, 85, 80, 85, 78, 83, 80, 85, 80, 85, 78, 83]
            right_eyebrow: [80, 85, 80, 85, 78, 83, 80, 85, 80, 85, 78, 83, 80, 85, 80, 85, 78, 83, 80, 85, 80, 85, 78, 83]
            mouth: [20, 25, 20, 25, 21, 26, 21, 26, 20, 25, 20, 25, 21, 26, 21, 25, 20, 24, 20, 25, 21, 26,21,26]
        time: 50.0
        #time in miliseconds
    talk1:
        servos:
            mouth: [10, 70, 10, 90, 50]
        time: 110.0
        #time in miliseconds
    talk2:
        servos:
            mouth: [30, 80, 20, 60]
        time: 110.0
        #time in miliseconds
    test2:
        #LEDs colors
        eyes:   
            left: [[yellow2, yellow2, yellow2, yellow2, black, black, black, black, yellow2, yellow2, yellow2, black, black, black, black, black]]
            right: [[yellow2, yellow2, yellow2, yellow2, black, black, black, black, yellow2, yellow2, yellow2, black, black, black, black, black]]
        #Servos positions in percentage. Meanings: ears: elevation %, eyebrow: 0%->angry & 100%->very surprised, mouth: opening %
        servos:
            left_ear: [70, 45, 70, 45, 70, 70, 70, 70, 45, 55, 70, 70, 70, 70, 55, 70, 45, 70]
            right_ear: [70, 45, 70, 45, 70, 70, 70, 70, 45, 55, 70, 70, 70, 70, 55, 70, 45, 70]
            left_eyebrow: [45]
            right_eyebrow: [45]
            mouth: [10, 70, 10, 90, 10, 10, 10, 10, 70, 90, 10, 10, 10, 10, 90, 10, 90, 10]
        time: 110.0
        #time in miliseconds
    calibrate_eyebrows:
        #Servos positions in percentage. Meanings: ears: elevation %, eyebrow: 0%->angry & 100%->very surprised, mouth: opening %
        servos:
            left_eyebrow: [0, 20, 40, 60, 80, 100, 80, 60, 40, 20, 0]
            right_eyebrow: [0, 20, 40, 60, 80, 100, 80, 60, 40, 20, 0]
        time: 400.0
        #time in miliseconds
