eye_colors:
  black : [0,0,0]
  #tonos 1
  white : [2,2,1]
  red : [2,0,0]
  green : [0,2,0]
  blue : [0,0,2]
  yellow : [2,2,0]
  cian : [0,2,1]
  magenta : [2,0,1]

  #tonos 2
  white2 : [4,4,2]
  red2 : [4,0,0]
  green2 : [0,4,0]
  blue2 : [0,0,2]
  yellow2 : [4,4,0]
  cian2 : [0,4,2]
  magenta2 : [4,0,2]

  #tonos 3
  white3 : [6,7,3]
  red3 : [8,0,0]
  green3 : [0,8,0]
  blue3 : [0,0,3]
  yellow3 : [8,8,0]
  cian3 : [0,8,3]
  magenta3 : [8,0,3]
