unknown_class: unknown 
food_smallest: soap
food_biggest: biscuits
food_lightest: sponge
food_heaviest: lotion
drink_smallest: yogurt
drink_biggest: orangejuice
drink_lightest: water
drink_heaviest: beer
object_smallest: soap
object_biggest: biscuits
object_lightest: toothpaste
object_heaviest: beer

classes : ["drinks","food","snacks","cleaningstuff","containers"]
drinks: ["greentea", "papayamilk", "puremilk", "water","orangejuice","beer","yogurt"]
food:   ["biscuits","bubblegum","chocolates","tomatochips","barbecuechips","honeychip","pringles"]
snacks: ["coconutcereals","cocoballs","eggstars","gramsoup","beansauce","apple","lemon","pear","mate"]
cleaningstuff: ["sponge","toiletpaper","soap","lotion","toothpaste","cloth"]
containers: ["bowl","plate","tray"]

unknown: []
unknown_location: waste_bin
drinks_location: kitchencounter
food_location: kitchentable
snacks_location: desk
cleaningstuff_location: bookcase
containers_location: kitchencounter


classes_color : ["blue","red","yellow","back","white"]
blue: ["greentea", "papayamilk", "puremilk", "water","orangejuice","beer","yogurt"]
red:   ["biscuits","bubblegum","chocolates","tomatochips","barbecuechips","honeychip","pringles"]
yellow: ["coconutcereals","cocoballs","eggstars","gramsoup","beansauce","apple","lemon","pear","mate"]
back: ["sponge","toiletpaper","soap","lotion","toothpaste","cloth"]
white: ["bowl","plate","tray"]
