# rosaria configuration

port: /dev/bender/base
<<<<<<< HEAD
tf_prefix: bender

RevCount: 531
odom_frame: bender/odom
base_link_frame: bender/base_link
=======
odom_frame: bender/odom
base_link_frame: bender/base_link
>>>>>>> 6e473d88e845aae672db291c0d8eba540b833462
