# known objects for Pick & Place behavior from Basic Functionalities test
# all other recognized object will be considered unknown  

unknown_class: unknown 
#classes: ["drinks", "food"]
classes: ["drinks", "food", "unknown"]

drinks: ["beer", "milk", "orange_juice"]
food: ["coffee", "noodles"]
unknown: ["brush", "detergent", "shampoo", "sponge", "tooth_paste", "cola", "chocolate_milk", "energy_drink", "grape_juice", "water", "chips", "biscuits", "bread", "chocolate_coockies", "pringles", "strawberry_coockies", "baby_food", "beans", "crackers", "yeast"]

unknown_location: waste_bin
drinks_location: bar
food_location: kitchen_counter