gotothe: "go to the"
offera: "offer a"
atthe: "at the"
inthe: "in the"
bringa: "bring a"
totheperson: "to the person"
followher: "follow"
followhim: "follow"
answeraquestion: "answer a question"
answerheraquestion: "answer a question"
answerhimaquestion: "answer a question"
tellthetime: "tell the time"
takethisobject: "take this object"
whichisinthe: "which is in the"
bringit: "bring it"
bringito: "bring it to"
bringthemto: "bring them to"
takethemto: "take them to"
countthe: "count the"
reportto: "report to"
reporttome: "report to me"
graspthe: "grasp the"
findaperson: "find a person"
tellhim: "tell him"
tellher: "tell her"
thewaving: "the waving"
findthewaving: "find the waving"
takeitto: "take it to"
thedayoftheweek: "the day of the week"
thedayofthemonth: "the day of the month"
whatdayistomorrow: "what day is tomorrow"
whatdayistoday: "what day is today"
thedate: "the date"
whattimeisit: "what time is it"
thetime: "the time"
thenameofyourteam: "the name of your team"
yourname: "your name"
takethe: "take the"
getthe: "grasp the"
geta: "grasp"
fromthe: "from the"
tothe: "to the"
getintothe: "go the"
navigateto: "go to"
bringitto: "bring it to"
deliveritto: "deliver it to"
takethis: "take this"
whichisinthe: "which is in the"
nearthe: "near the"
nextothe: "nex to the"
onthe: "on the"
bringthe: "bring the"
takea: "take a"
comeback: "come back"
tellittome: "tell it to me"
tothepersonthere: "to the person there"
cometome: "come to me"