#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import division

__author__ = 'Giovanni Pais'
__email__ = 'giom.pais@gmail.com'

import rospy
from moveit_python import MoveGroupInterface

from geometry_msgs.msg import Pose, PoseStamped, Point




#TEST para movimiento con skill en espacio de joint
def main():
    
    
    g = MoveGroupInterface("l_arm", "bender/base_link",None,False)

    joint_names=['l_shoulder_pitch_joint', 'l_shoulder_roll_joint',
      'l_shoulder_yaw_joint', 'l_elbow_pitch_joint', 'l_elbow_yaw_joint',
      'l_wrist_pitch_joint']
    
    rospy.loginfo('INICIA TEST')
    home =[0.0,0.0,0.0,0.0,0.0,0.0]
    pos_1=[-0.3352, 0.0, 0.0, -0.7056, -0.0410, -0.4763]
    l_arm_premanip_1=[0.9702, 0.0, 0.0, -1.5700, -0.041, -0.9526]
    
    

    #Movimiento en espacio de joint
    g.moveToJointPosition(joint_names,home)
    rospy.sleep(2.0)
    rospy.loginfo('POSITION: HOME')
    rospy.sleep(1.0)
    g.moveToJointPosition(joint_names,l_arm_premanip_1)
    rospy.sleep(2.0)
    rospy.loginfo('POSITION: l_arm_premanip_1')
    g.moveToJointPosition(joint_names,pos_1)
    rospy.sleep(2.0)
    rospy.loginfo('POSITION: pos_1')
    g.moveToJointPosition(joint_names,home)
    rospy.sleep(2.0)
    rospy.loginfo('POSITION: HOME')
    rospy.loginfo('TERMINA TEST')
    ################################


if __name__ == '__main__':
    rospy.init_node('planning_tester')
    main()