mesa_1:
  x: -3.15
  y: 0.57
  z: 0.1
  yaw: 1.59

mesa_2:
  x: 3.62
  y: 0.69
  z: 0.1
  yaw: 1.59

mesa_3:
  x: -3.42
  y: -0.35
  z: 0.1
  yaw: -1.58

mesa_4:
  x: 3.16
  y: -0.42
  z: 0.1
  yaw: -1.58
