# Config for test head port
namespace: head_port_manager
serial_ports:
  head_port:
    port_name: "/dev/bender/head_port"
    baud_rate: 1000000
    min_motor_id: 1
    max_motor_id: 10
    update_rate: 30