unknown_class: unknown 

eliminate: ["the", "a", "and","for","into"]

actions: ["go","grasp","bring","find","offer","count","report","introduce","answer","guide","put","say","ask","follow","return", "waving", "calling","take", "look"]

names: ["alex","angel","edward","homer","jamie","john","kevin","kurt","tracy","robin","alex","angel","eve","jamie","jane","liza","melissa","tracy","robin","sophia"]

location: ["kitchen","livingroom","bedroom","hallway","me","door","exit","there"]
manipulate_location: ["kitchentable","kitchencounter","desk","bookcase", "trashbin","cupboard","couchtable","dinnertable","left bedside table","right bedside table","hallwaytable"]

item_category : ["drinks","food"]
drinks: ["beer", "milk", "orange_juice","coke"]
food: ["coffee", "noodles","pringles","cookies","crackers", "pear", "orange", "apple", "banana"]

drinks: ["greentea", "papayamilk", "puremilk", "water","orangejuice","beer"]
food:   ["biscuits","bubblegum","chocolates","tomatochips","barbecuechips","honeychip","coconutcereals","cocoballs","eggstars","gramsoup","beansauce","apple","lemon","pear","sponge","toiletpaper","soap","lotion","toothpaste","cloth"]

unknown: []

unknown_location: waste_bin
drinks_location: bar
food_location: kitchen_counter
