# hokuyo laserscan configuration for urg_node ROS node
#
# on bender: frontal laser (Hokuyo UTM-30LX)
# 

# connection
serial_port: /dev/bender/sensors/hokuyo_H1311689   # orange
#serial_port: /dev/bender/sensors/hokuyo_H0804550   # blue
#serial_port: /dev/bender/sensors/hokuyo_H0903381   # black
#serial_port: /dev/ttyACM1 # if the udev rule is not working properly anymore

# frame
frame_id: /bender/sensors/laser_front_link

# angles in radians
angle_max:  2.01  # ~  115 [deg]
angle_min: -2.01  # ~ -115 [deg]

# force 20 Hz
skip: 1

# Whether the node should calibrate the device's time offset on startup.
# If true, the node will exchange of series of messages with the device
# in order to determine the time delay in the connection. This calibration
# step is necessary to produce accurate timestamps on scans. 
calibrate_time: true

# output NaN values as inf.
# PS. Obtained from a pull request. Not on the official doc.
no_range_as_inf: true

# enforce defaults
ip_address: ""
ip_port: 10940
serial_baud: 115200
allow_unsafe_settings: false
cluster: 1
time_offset: 0.0
get_detailed_status: false
publish_intensity: false
publish_multiecho: false
diagnostics_tolerance: 0.05
diagnostics_window_time: 5.0

#	max_ang_limit:	read-only
#	min_ang_limit:	read-only
#	max_range:	read-only
#	min_range:	read-only

