scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: angular_bounds_filter
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: 0.52
        upper_angle: -0.52
