
frame_id: /bender/sensors/laser_front_link
max_ang:  2.01  # ~ -115 [deg]
min_ang: -2.01  # ~  115 [deg]
port: /dev/sensors/hokuyo_H1311689   # orange
#port: /dev/sensors/hokuyo_H0804550   # blue
#port: /dev/sensors/hokuyo_H0903381   # black


allow_unsafe_settings: false
calibrate_time: true
cluster: 1
intensity: false
time_offset: 0.0
skip: 0

#	max_ang_limit:	read-only
#	min_ang_limit:	read-only
#	max_range:	read-only
#	min_range:	read-only

