head_controller:
    controller:
        package: bender_mask_head
        module: joint_trajectory_action_controller
        type: JointTrajectoryActionController
    joint_trajectory_action_node:
        joint_states_topic: 'head/joint_states'
        min_velocity: 0.1
        constraints:
            goal_time: 0.25

