head_yaw_joint_controller:
  controller:
    module: joint_position_controller
    package: dynamixel_controllers
    type: JointPositionController
  joint_name: head_yaw_joint
  joint_speed: 0.8
  motor:
    id: 30
    init: 425
    max: 795
    min: 55
head_pitch_joint_controller:
  controller:
    module: joint_position_controller
    package: dynamixel_controllers
    type: JointPositionController
  joint_name: head_pitch_joint
  joint_speed: 0.8
  motor:
    id: 31
    init: 682
    max: 855
    min: 605
