unknown_class: unknown

eliminate: ["the", "a", "an", "and","for","bring","me", "give", "i", "with", "would", "like"]

item_category : ["milk","snackfruit","cereal"]

cereal : ["chocoflakes","flakes","froot_loops","cheerios","trix","frosties"]
snackfruit: ["apple","peach","banana","pineapple","orange","kiwi_fruit"]
milk: ["chocolate_milk","light_milk","lactose_free_milk","strawberry_milk","fat_free_milk"]

unknown: ["brush", "detergent", "shampoo", "sponge", "tooth_paste", "cola", "chocolate_milk", "energy_drink", "grape_juice", "water", "chips", "biscuits", "bread", "chocolate_cookies", "pringles", "strawberry_cookies", "baby_food", "beans", "crackers", "yeast"]


