controller_list:
  - name: l_arm_contoller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: [l_shoulder_pitch_joint, l_shoulder_roll_joint, l_shoulder_yaw_joint, l_elbow_pitch_joint, l_elbow_yaw_joint, l_wrist_pitch_joint]