# Config for r_arm, r_gripper and rgbd head
namespace: r_arm_manager
serial_ports:
  r_arm_port:
    port_name: "/dev/bender/right_arm"
    baud_rate: 200000
    min_motor_id: 11
    max_motor_id: 21
    update_rate: 30