sensor_msgs/Image image
sensor_msgs/Image[] faces
bender_msgs/Rect[] BBoxes
bender_msgs/Rect[] eyes_positionL
bender_msgs/Rect[] eyes_positionR
int32 n_faces
bool simulate_eyes
---
string[] gender
int8[] eyes_used
int32 n_faces
int8 n_men
int8 n_women

