# srv utilizado por el package: uchile_nav
# Representa un 'goal' a perseguir y un feedback.

# Request: goal representado por a) o b) (no ambos)
# a) pose en el espacio
# b) angulos a rotar (grados)
geometry_msgs/PoseStamped goal
---
# Response
int32 state    # Current goal state
               # 0: (GOAL_WAITING)  Waiting for next goal
               # 1: (GOAL_WALKING)  Moving toward goal
               # 2: (GOAL_ALMOST_REACHED) In rotation adjustment phase
               # 3: (GOAL_REACHED)  Reached OK.
               # 4: (GOAL_ABORTED)  Goal aborted by the server.
               # 5: (GOAL_CANCELED) Goal aborted by the user.